# --- Project --- #
project_name : "turnover_behavior"
description : ""
author : "jinheon yoon"
email : "yjinheon@gmail.com"


# --- Initial Setting --- #
data_directory: "./data/"
data_name: "code_labels_goms_2018.csv"
drop_columns: ["id"]
target_name: "diagnosis"
test_size: 0.3
random_state: 42
model_directory: "./Model"
model_name: KNN_classifier.pkl


# hyperarameters
n_neighbors: 3
weights: uniform
algorithm: auto
leaf_size: 15
p: 2
metric: minkowski
n_jobs: 1